ci:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/workflows/**"
          - ".github/**"
          - "package.json"
          - "pnpm-lock.yaml"

platform:
  - changed-files:
      - any-glob-to-any-file:
          - "THIRD_PARTY_NOTICES.md"
          - "packages/desktop-electron/**"

app:
  - changed-files:
      - any-glob-to-any-file:
          - "packages/desktop-electron/resources/dsh/**"
          - "README.md"
          - "README_CN.md"

ui:
  - changed-files:
      - any-glob-to-any-file:
          - "packages/desktop-electron/resources/dsh/product/**"
          - "site/**"
